language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial

env:
  global:
    - BOTO_CONFIG=/dev/null
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - brume --version
  - brume --help
  - python setup.py test
